logging:
  level:
    ru.gosuslugi.im.ws: DEBUG
    org:
      springframework:
        ws: DEBUG
server:
  port: 8080
client.default-uri: http://localhost:8080/ws/ThirdPartyOrderService
signature:
  privateKey:
    alias: alias
    password: password
  certificate:
    alias: alias
security:
  basic:
  enabled: false